version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: contact_form_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: